spring.application.name=blog-app-apis

server.port = 9091

# db configuration

spring.datasource.driver-class-name= com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update


#create, update, create-drop, validate
#spring.jpa.hibernate.ddl-auto: 
#It controls how Hibernate handles your database schema (tables, columns, etc.)

spring.servlet.multipart.max-file-size = 10MB
spring.servlet.multipart.max-request-size = 10MB

project.image = images/

# security logging
logging.level.org.springframework.security=DEBUG
#
#spring.security.user.name = admin
#spring.security.user.password = admin
#spring.security.user.roles = ADMIN


spring.profiles.active=dev